name: Email Step Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 22f3002676@ds.study.iitm.ac.in
        run: echo "Hello, world!"
